#!/bin/bash

# 创建保存模型的目录
mkdir -p /workspace/facefusion/.assets/models

# 下载并保存模型文件
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/arcface_converter_hififace.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/arcface_converter_hififace.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/hififace_unofficial_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/hififace_unofficial_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/realistic_rescaler_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/realistic_rescaler_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/real_web_photo_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/real_web_photo_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/remacri_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/remacri_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/siax_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/siax_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/styleganex_age.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/styleganex_age.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/swin2_sr_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/swin2_sr_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/xseg_groggy_5.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.1.0/xseg_groggy_5.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/2dfan4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/2dfan4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/arcface_converter_ghost.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/arcface_converter_ghost.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/arcface_converter_simswap.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/arcface_converter_simswap.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/arcface_w600k_r50.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/arcface_w600k_r50.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/bisenet_resnet_34.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/bisenet_resnet_34.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/blendswap_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/blendswap_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/clear_reality_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/clear_reality_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/codeformer.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/codeformer.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ddcolor.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ddcolor.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ddcolor_artistic.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ddcolor_artistic.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/deoldify.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/deoldify.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/deoldify_artistic.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/deoldify_artistic.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/deoldify_stable.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/deoldify_stable.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/dfl_xseg.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/dfl_xseg.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/fairface.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/fairface.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/fan_68_5.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/fan_68_5.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gfpgan_1.2.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gfpgan_1.2.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gfpgan_1.3.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gfpgan_1.3.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gfpgan_1.4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gfpgan_1.4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ghost_1_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ghost_1_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ghost_2_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ghost_2_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ghost_3_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ghost_3_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_1024.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_1024.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_2048.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_2048.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_512.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/gpen_bfr_512.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/kim_vocal_2.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/kim_vocal_2.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_eye_retargeter.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_eye_retargeter.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_feature_extractor.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_feature_extractor.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_generator.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_generator.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_lip_retargeter.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_lip_retargeter.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_motion_extractor.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_motion_extractor.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_stitcher.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/live_portrait_stitcher.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/lsdir_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/lsdir_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/nomos8k_sc_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/nomos8k_sc_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/open_nsfw.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/open_nsfw.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/peppa_wutz.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/peppa_wutz.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x2.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x2.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x2_fp16.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x2_fp16.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x4_fp16.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x4_fp16.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x8.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x8.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x8_fp16.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_esrgan_x8_fp16.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_hatgan_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/real_hatgan_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/restoreformer_plus_plus.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/restoreformer_plus_plus.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/retinaface_10g.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/retinaface_10g.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/scrfd_2.5g.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/scrfd_2.5g.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/simswap_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/simswap_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/simswap_unofficial_512.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/simswap_unofficial_512.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/span_kendata_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/span_kendata_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ultra_sharp_x4.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/ultra_sharp_x4.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/uniface_256.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/uniface_256.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/wav2lip_96.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/wav2lip_96.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/wav2lip_gan_96.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/wav2lip_gan_96.onnx
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/yoloface_8n.hash
wget -P /workspace/facefusion/.assets/models https://ghp.ci/https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/yoloface_8n.onnx
